sky:
  datasource:
    #数据库配置文件
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: *
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    #阿里云oss配置
    endpoint: *
    access-key-id: *
    access-key-secret: *
    bucket-name: *
  wechat:
    appid: *
    secret: *
    mchid: *
    mchSerialNo: *
    privateKeyFilePath: *
    apiV3Key: *
    weChatPayCertFilePath: *
    notifyUrl: *
    refundNotifyUrl: *
