sky:
  datasource:
    #数据库配置文件
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: he020724
  alioss:
    #阿里云oss配置
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-take-out
